name: Exemple
on:
  push:
    branches:
      - 'main'
jobs:
   container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure .npmrc for Artifactory
        run:  |
          echo "email = fouzia.merain@gmail.com"> .npmrc
          echo "always-auth = true" >> .npmrc
          echo "registry=https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/" >> .npmrc
          echo "//https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/:authToken=${{ secrets.JFROG_DOCKER_TOKEN }}" >> .npmrc
     
      - run: npm publish
