name: Build and push nodejs app to artifactory

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Configure artifactory
        env:
          ARTIFACTORY_USER_EMAIL: ${{ secrets.ARTIFACTORY_USER_EMAIL }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run:
          |
          echo "email = $ARTIFACTORY_USER_EMAIL
                always-auth = true
                registry=https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/
                //$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/:_authToken=$ARTIFACTORY_PASSWORD" > ~/.npmrc

      - name: Push to artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: npm publish --registry https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/
