name: Exemple
on:
  push:
    branches:
      - 'main'
jobs:
   container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm config set registry https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/:always-auth true
      - run: npm config set _auth ${{ secrets.JFROG_DOCKER_TOKEN }} 
      - run: npm config set email=fouzia.merain@gmail.com
      - run: npm publish
