name: Exemple
on:
  push:
    branches:
      - 'main'
jobs:
   container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure .npmrc for Artifactory
        run:  |
          echo "registry=https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/"> .npmrc
          AUTH_INFO=$(echo -n "${{ secrets.JFROG_DOCKER_TOKEN }}" | base64)
          echo "//https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/:authToken=$AUTH_INFO" >> .npmrc
     
      - run: npm publish
